version: 2

project_name: jwt-gen

before:
  hooks:
    - go mod tidy

builds:
  - id: jwt-gen
    main: ./jwt-generator.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: jwt-gen

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_{{ .Arch }}
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: 'checksums_{{ .Version }}.txt'
  algorithm: sha256

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs?:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  prerelease: auto
